### ISSUE TITLE
مشکل با نیم فاصله

### ISSUE THREAD

**Issue by habibmousavi** [hosseinmousavi/Regex.Persian.Language#1]
سلام دوست عزیز. ممنون بابت کار بسیار با ارزش‌تان. فقط میخواستم یک نکته عرض کنم؛ و آنکه موقع بررسی عبارات منظم، علیرغم استفاده از کدهای شما، باز هم نمی‌توانم نیم فاصله رو ارزیابی کنم. 
این کد من است.
`function NameValidity ($name) {
        $space_codepoints = '\x{0020}\x{2000}-\x{200F}\x{2028}-\x{202F}';
        $persian_alpha_codepoints = '\x{0621}-\x{0628}\x{062A}-\x{063A}\x{0641}-\x{0642}\x{0644}-\x{0648}\x{064E}-\x{0651}\x{0655}\x{067E}\x{0686}\x{0698}\x{06A9}\x{06AF}\x{06BE}\x{06CC}';
        return preg_match('/^['.$space_codepoints.$persian_alpha_codepoints.']*$/u', $name);
	}`
من برای نیم فاصله کلیدهای کنترل+شیفت+2 رو فشار میدم. شما برا نیم فاصله کلیدهای ترکیبی دیگری رو می‌زنین؟ ممکنه راهنمایی بفرمایید چکار کنم.
سپاس

**Comment by hosseinmousavi** [comment]
سلام دوست خوبم
باید عبارات منظم فاصبه رو هم اضافه کنید
```python
import re
input='‌ایران‌ی'
space_codepoints ='\u0020\u2000-\u200F\u2028-\u202F'
persian_alpha_codepoints = '\u0621-\u0628\u062A-\u063A\u0641-\u0642\u0644-\u0648\u064E-\u0651\u0655\u067E\u0686\u0698\u06A9\u06AF\u06BE\u06CC'


result=re.search('^['+space_codepoints+persian_alpha_codepoints+']*$', input)
assert result
```

**Comment by habibmousavi** [comment]
سلام. سپاس از پاسخگویی حضرتعالی
اگر دقت بفرمایید در کد پی اچ پی من همین کار رو کردم. الان حروف فارسی و فاصله مشکلی ندارن در خروجی کار. اما نیم فاصله (با کلیدهای ترکیبی کنترل شیفت و 2) جز اون کلیدها شناسایی نمیشه. 
لطفاً راهنمایی فرمایید. 
سپاس مجدد از محبت شما

**Comment by hosseinmousavi** [comment]
من تو سایت ویندوز نتونستم چیزی پیدا میکنم ولی طبق [این لینک](http://sartre2.byu.edu/persian/persianword/zwnj.htm)
کاراکتری که Ctrl + Shift + 2 تولید میکنه Zero-Width Non-Joiner هست
که تو همین عبارات منظم فاصله قرار داده شده
من نیم فاصله رو تو ویندوز 10 با همین میانبر ایجاد کردم به من خروجی 1 داد این کد
```php
function NameValidity ($name) { 
	$space_codepoints = '\x{0020}\x{2000}-\x{200F}\x{2028}-\x{202F}';
	$persian_alpha_codepoints = '\x{0621}-\x{0628}\x{062A}-\x{063A}\x{0641}-\x{0642}\x{0644}-\x{0648}\x{064E}-\x{0651}\x{0655}\x{067E}\x{0686}\x{0698}\x{06A9}\x{06AF}\x{06BE}\x{06CC}'; 
	return preg_match('/^['.$space_codepoints.$persian_alpha_codepoints.']*$/u', $name);
}
# half space between two character by Ctrl + Shift + 2
$name = 'س‌ل';
print_r(NameValidity($name));
```

**Comment by habibmousavi** [comment]
سلام دوست عزیز؛ بله حق با شماست. من به اشتباهم پی بردم. من در اصل داشتم عبارات منظم حروف فارسی و نیم فاصله رو برای یک ورودی «نام» چک می‌کردم. مشکل از کد یک فانکشن دیگه من بود. من برای سنیتایز کردن ورودی ها از htmlentities استفاده می کردم که این دستور کلید کنترل شیفت 2 رو تبدیل به یک کاراکتر دیگه می‌کرد و عبارات منظم نمی تونستن اون رو تشخیص بدن. من به جای htmlentities از htmlspecialchars استفاده کردم و مشکل حل شد. باز هم سپاس از شما
